# Generated by Django 5.0.1 on 2024-03-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Source',
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Source'},
        ),
    ]
